# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# Ubuntu:
# sudo apt-get install arduino-mk python-serial

USER_LIB_PATH=../lib

ARDUINO_LIBS=Wire SPI Arduino-MPU6050 RF24 Encoder

#BOARD_TAG    = uno
BOARD_TAG = pro328

include /usr/share/arduino/Arduino.mk
